SLACK_CHANNEL_NAME: 'build-status'
ENVIRONMENT: 'prod'
CODE_BASE_PATH: 'env/prod'
ACTION_MESSAGE: 'Deployment completed successfully'
KEEP_APPROVAL_STAGE: true
GIT_REPO: 'https://github.com/askankita19-jpg/Opstree-Batch-33.git'
PLAYBOOK_NAME: 'kube_playbook.yml'
